import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

import Header from './components/header'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          class_name='header-bg'
          title='합리적인 가격에 고성능 서버를 상담받아보세요.'
          subtitle=''
        />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
